dep:
  train_dataset: "@BASE(dataset)"
  val_source_dataset: "@BASE(dataset)"
  val_target_dataset: "@BASE(dataset)"
  img_size: !!python/tuple [512, 1024]
  train_dep_size: !!python/tuple [512, 1024]
  val_dep_size: !!python/tuple [1024, 2048]
  train_bs: 2
  val_bs: 2
  lr: 1e-4
  num_epochs: 70

sem:
  train_dataset: "@BASE(dataset)"
  val_source_dataset: "@BASE(dataset)"
  val_target_dataset: "@BASE(dataset)"
  img_size: !!python/tuple [512, 1024]
  train_sem_size: !!python/tuple [512, 1024]
  val_sem_size: !!python/tuple [1024, 2048]
  train_bs: 2
  val_bs: 2
  lr: 1e-3
  num_epochs: 100

transfer:
  train_dataset: "@BASE(dataset)"
  val_source_dataset: "@BASE(dataset)"
  val_target_dataset: "@BASE(dataset)"
  img_size: !!python/tuple [512, 1024]
  train_sem_size: !!python/tuple [512, 1024]
  val_sem_size: !!python/tuple [1024, 2048]
  train_bs: 2
  val_bs: 2
  lr: 1e-3
  num_epochs: 100
  num_classes: 19
  ignore_index: 19
  dep_ckpt_path: logs/d4dep/ckpt.pt
  sem_ckpt_path: logs/d4sem/ckpt.pt
