dep:
  train_dataset: "@BASE(dataset)"
  val_source_dataset: "@BASE(dataset)"
  val_target_dataset: "@BASE(dataset)"

  img_size: !!python/tuple [512, 1024]
  train_dep_size: !!python/tuple [512, 1024]
  val_dep_size: !!python/tuple [1024, 2048]

  dep_range: !!python/tuple [0.01, 60]
  dep_cmap: "plasma"

  train_bs: 2
  val_bs: 2
  lr: 1e-4
  num_epochs: 70

sem:
  train_dataset: "@BASE(dataset)"
  val_source_dataset: "@BASE(dataset)"
  val_target_dataset: "@BASE(dataset)"

  img_size: !!python/tuple [512, 1024]
  train_sem_size: !!python/tuple [512, 1024]
  val_sem_size: !!python/tuple [1024, 2048]

  sem_num_classes: 19
  sem_ignore_index: 19
  sem_cmap: "cmap19"

  train_bs: 2
  val_bs: 2
  lr: 1e-4
  num_epochs: 70

transfer:
  train_dataset: "@BASE(dataset)"
  val_source_dataset: "@BASE(dataset)"
  val_target_dataset: "@BASE(dataset)"

  img_size: !!python/tuple [512, 1024]
  train_sem_size: !!python/tuple [512, 1024]
  val_sem_size: !!python/tuple [1024, 2048]

  sem_num_classes: 19
  sem_ignore_index: 19
  sem_cmap: "cmap19"

  train_bs: 2
  val_bs: 2
  lr: 1e-4
  num_epochs: 30
